### ISSUE TITLE
Add organizer contacts onto group pages

### ISSUE THREAD

**Issue by lannonbr** [syracuseio/syracuseio#66]
What do people think about having pages specifically for the leaders of our community / organizers of the various events. On these pages we can list social links as well as what they do as a job and events they put on. Then we can link these pages to the groups.

For example. We could make a page for @joeybuczek and then if someone goes to the SyrJS meetup page, they could see Joey runs it and they could go to him if they have a question about the SyrJS meetup.

Would people be alright with this?

**Comment by annalenadavis** [comment]
Maybe instead of a separate page for each organizer/leader, the people could be listed on the "Learn More" page for each type of event. For example at https://syracuse.io/groups/women_in_coding/ you could list Zoe, Christy, and myself with either a social link, or email or some way to contact us. For WIC you can link to the contact page on our website http://womenincoding.com/contact.html

**Comment by joeybuczek** [comment]
I'm in favor of Annalena's suggestion. If in the future one the meetups gets handed over to someone else to manage, then you dont need to update personal profiles, etc, just update the event info

**Comment by lannonbr** [comment]
Okay. Thanks for the suggestions! I'll look into a prototype for this and then push a PR up for people to review before merging it in

**Comment by lannonbr** [comment]
PR is up. If anyone wishes to go review the design or code for this, head over to the PR. In the Check Suite portion at the bottom, there's a `deploy/netlify` entry which will show a live preview of the site with the new changes.

Currently I only added Jesse to the Hack Upstate page, but once this is merged, other organizers can follow the example to add their own details / links and submit new PRs for it
